# File format: https://github.com/toml-lang/toml

#
# Usually this file extends base configuration defined messenger-bridge.toml
#

[io.edgebus.messenger-bridge.runtime]

	[io.edgebus.messenger-bridge.runtime.cache]
		# url = "memory://"
		url = "redis://127.0.0.1:52001/0"

	[io.edgebus.messenger-bridge.runtime.database]
		url = "postgres://edgebus-local-messenger-bridge@127.0.0.1:52000/edgebus-local"
		#url = "memory://"
		#user = "dev"
		#password = "devel"

	[io.edgebus.messenger-bridge.runtime.approvement]

		[[io.edgebus.messenger-bridge.runtime.approvement.topic]]
			index = "DeployProduction"
			description = "Requests to deploy new version of an application."
			requireVotes = 1
			expireTimeout = 3600
			#authType = "???TBD???"
			schema = """
	{
		"appName", "appVersion"
	}
	"""

	[[io.edgebus.messenger-bridge.runtime.messenger]]
		index = "bot1"
		type = "telegram"
		#apiToken =
		approvementTopicBinding_indexer = "topicBinding1"

		[[io.edgebus.messenger-bridge.runtime.messenger.approvementTopicBinding]]
			index = "topicBinding1"
			bindTopic = "DeployProduction"
			#chatId = <Telegram's Unique identifier for the target chat or username of the target channel (in the format @channelusername)>
			#approvers = "user1 user2 user3 userN" // all users if missing
			renderTemplate = """
<b>Do you allow deploy to production?</b>
<i>Application: </i><b>{{appName}}</b>
<i>Version: </i><b>{{appVersion}}</b>
Pls, Ignore this test message (detecting memory leaks)
"""
