# File format: https://github.com/toml-lang/toml

[io.edgebus.messenger-bridge.runtime]

	[[io.edgebus.messenger-bridge.runtime.server]]
		# Declare an API HTTP server
		index = "apiSrv"
		type = "http"
		listenHost = "0.0.0.0"
		listenPort = 8080

	[[io.edgebus.messenger-bridge.runtime.endpoint]]
		index = "infoEndpoint"
		type = "info"
		servers = "apiSrv"
		bindPath = "/info"

	[[io.edgebus.messenger-bridge.runtime.endpoint]]
		index = "monitoringEndpoint"
		type = "monitoring"
		servers = "apiSrv"
		bindPath = "/metrics"

	[[io.edgebus.messenger-bridge.runtime.endpoint]]
		# Declare REST endpoint and bound to the API HTTP server on path /v1
		index = "restEndpoint"
		type = "rest"
		servers = "apiSrv"
		bindPath = "/v1"

	[[io.edgebus.messenger-bridge.runtime.endpoint]]
		# Declare Welcome Page endpoint and bound to the API HTTP server on path /
		index = "welcomeEndpoint"
		type = "welcome-page"
		servers = "apiSrv"
		bindPath = "/" 

	[[io.edgebus.messenger-bridge.runtime.endpoint]]
		# Declare WebSocket endpoint and bound to the API HTTP server on path /ws1
		index = "wsEndpoint"
		type = "websocket"
		servers = "apiSrv"
		bindPath = "/ws1"
